### ISSUE TITLE
problem with DDString

### ISSUE THREAD

**Issue by doronhi** [awesomebytes/ddynamic_reconfigure#2]
hi,
Thanks for sharing this code.
I tried to copy the example given in the README.md file and had a problem with rqt_reconfigre:
`
doronhi@ubuntu:~$ rosrun rqt_reconfigure rqt_reconfigure 
`
I then try to open the object in the rqt_reconfigure's GUI and get this error:

[ERROR] [1540211050.795114]: bad callback: <bound method Client._descriptions_msg of <dynamic_reconfigure.client.Client object at 0x7fb137260050>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/client.py", line 338, in _descriptions_msg
    self._param_types[n] = self._param_type_from_string(t)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/client.py", line 355, in _param_type_from_string
    raise DynamicReconfigureParameterException('parameter has unknown type: %s. This is a bug in dynamic_reconfigure.' % type_str)
DynamicReconfigureParameterException: parameter has unknown type: string. This is a bug in dynamic_reconfigure.

I tried removing the string parameter and everything else works.
 
I tried running:
`
rosrun ddynamic_reconfigure_python example.py
`
It also shows a string parameter but everything works fine now.

It seems to me that something is different in the way python and C++ implements the DDString object. 
Or, any suggestions as to what am doing wrong?

Attached is my code:

void MyNode::registerDynamicReconfigCb(ros::NodeHandle& nh)
{
    ROS_INFO("Setting Dynamic reconfig parameters.");
    // DDynamic setup stage
    _dd = std::make_shared<ddynamic_reconfigure::DDynamicReconfigure>(nh);
    _dd->add(new DDInt("int_param", 0, "An Integer parameter", 50, 0, 100));
    _dd->add(new DDDouble("double_param", 0, "A double parameter", .5, 0, 1));
    _dd->add(new DDString("str_param", 0, "A string parameter", "Hello World"));
    _dd->start(callback);
    ROS_INFO("Done Setting Dynamic reconfig parameters.");
}

**Comment by doronhi** [comment]
Also, the example for the DDEnum didn't work for me.
When opened the matching group in : rosrun rqt_reconfigure rqt_reconfigure
I got the following error message in the rqt_reconfigure terminal:

doronhi@ubuntu:~/catkin_ws$ rosrun rqt_reconfigure rqt_reconfigure 
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/node_selector_widget.py", line 275, in _selection_changed_slot
    self._selection_selected(index_current, rosnode_name_selected)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/node_selector_widget.py", line 225, in _selection_selected
    item_widget = item_child.get_dynreconf_widget()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/treenode_qstditem.py", line 154, in get_dynreconf_widget
    self._param_name_raw)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/dynreconf_client_widget.py", line 67, in __init__
    group_desc, node_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/param_groups.py", line 152, in __init__
    self._create_node_widgets(config)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/param_groups.py", line 174, in _create_node_widgets
    widget = EnumEditor(self.updater, param)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/param_editors.py", line 423, in __init__
    self._combobox.setCurrentIndex(self.values.index(config['default']))
ValueError: 1 is not in list

Any ideas...?

**Comment by awesomebytes** [comment]
@wew84 You may want to take a look
